apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-deployment
  labels:
    app: apppython
spec:
  replicas: 2
  selector:
    matchLabels:
      app: apppython
  template:
    metadata:
      labels:
        app: apppython
    spec:
      containers:
      - name: apppython
        image: parshchakurkar/app_python:1.0
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: web-service
spec:
  selector:
    app: apppython
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000