trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, Docker!
  displayName: 'Run a one-line script'
- task: Docker@2
  inputs:
    containerRegistry: 'Dockerhub_parshchakurkar'
    repository: 'parshchakurkar / azure_docker'
    command: 'buildAndPush'
    Dockerfile: '**/Dockerfile'